### ISSUE TITLE
Generates `export default` instead of `export =`

### ISSUE THREAD

**Issue by lishaduck** [sxzz/rolldown-plugin-dts#79]
### Describe the bug

When using [`output.exports`](https://rollupjs.org/configuration-options/#output-exports)[^1] with `'default'` or `'auto'` (the latter is the default 😂), `rolldown-plugin-dts` should emit `export =` instead of `export default`, as there won't be a `.default` property on the resulting object (in my case, I need to use `'default'` to emit an ESLint plugin).
As it is, tsdown outputs ATTW errors: ["❗️ Incorrect default export"](https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/main/docs/problems/FalseExportDefault.md)

[^1]: [Rolldown docs](https://rolldown.rs/reference/config-options#exports) are... uh... lacking, so Rollup is linked.

### Reproduction

https://github.com/lishaduck/tsdown-cjs-dts-repro

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz
    Memory: 5.56 GB / 15.90 GB
  Binaries:
    Node: 24.2.0 - ~\AppData\Local\mise\installs\node\24.2.0\node.EXE
    Yarn: 1.22.19 - ~\AppData\Local\mise\installs\node\24.2.0\yarn.CMD
    npm: 11.3.0 - ~\AppData\Local\mise\installs\node\24.2.0\npm.CMD
    pnpm: 10.14.0 - ~\AppData\Local\mise\installs\node\24.2.0\pnpm.CMD
  Browsers:
    Edge: Spartan (44.19041.3570.0), Chromium (127.0.2651.86)
    Internet Explorer: 11.0.19041.5794
```

### Used Package Manager

pnpm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
Resolved both in tsdown and rolldown-plugin-dts. See https://tsdown.dev/options/cjs-default

**Comment by lishaduck** [comment]
That didn't seem to fix it for me. It looks like it doesn't handle type-only exports? (i.e., `export { type A, b as default}`)

**Comment by sxzz** [comment]
This is by design. `export =` cannot be used with any named exports, including type-only exports.

https://www.typescriptlang.org/play/?#code/KYDwDg9gTgLgBAXjgRgAwChSVnGBPMYOAFURVSA
